### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
### Verbo GET – listar todos
curl -X 'GET' \
    'http://localhost:8000/cliente/' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

### Verbo GET – listar um
GET http://localhost:8000/cliente/6 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
### Verbo GET – listar todos
curl -X 'GET' \
    'http://localhost:8000/cliente/' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
    "nome": "Eduarda Müller Machado",
    "cpf" : "07282850994",
    "telefone" : "49999650401",
    "compra_fiado" : 0,
    "dia_fiado" : "565465",
    "senha" : "duda2004"
}

### Verbo POST – listar todos
curl -X 'POST' \
    'http://localhost:8000/cliente/' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/6 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
    "nome": "Luciano Coelho",
    "cpf" : "012345678910",
    "telefone" : "09876543210",
    "compra_fiado" : 0,
    "dia_fiado" : "",
    "senha" : "cavuniplac1"
}

### Verbo PUT – listar todos
curl -X 'PUT' \
    'http://localhost:8000/cliente/' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
### Verbo DELETE – listar todos
curl -X 'DELETE' \
    'http://localhost:8000/cliente/' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'